let auditAction={
    SIGNUP:'SIGNUP',
    LOGIN:'LOGIN',
    UPD_USR:'UPD_USR',
    ADD_ADDRESS:'ADD_ADDRESS',
    ALL_ADDRESSES:'ALL_ADDRESSES',
    DEL_ADDRESS:'DEL_ADDRESS',
    AUTHENTICATION:'AUTHENTICATION'
}

module.exports={auditAction};